// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nibophsuecrpkeqyyulr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pYm9waHN1ZWNycGtlcXl5dWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzEzNDQsImV4cCI6MjA2MTk0NzM0NH0.e83LzvQdNw0BLJ-uOCSpSkBmGVMdYQqS4UI60W94xoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);